name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]
    steps:
    - name: Dump github context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - name: Run Makefile to build project artifacts
      run: make DOTNET_PUBLISH_ARGS=-maxcpucount:1
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/upload-artifact@v1
      with:
        name: event-sorcerer
        path: build
