name: CI

on: [push]

jobs:
  build-portable:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Run Makefile to build portable binaries
      run: make build-portable
