name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]

    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - name: Run Makefile to build project artifacts
      run: make build
    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: build
